behaviors:
  Mouse:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 1.0e-05
      beta: 1.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 1
    reward_signals:
      curiosity:
        gamma: 0.99
        strength: 0.995
    max_steps: 250000
    time_horizon: 64
    summary_freq: 10000